import numpy as np

varying_arg = {
    "seed": 42,
    "use_batch_norm": False,
    "use_layer_norm": False, 
    "step_size_lr": 45, 
    "attribute_dropout_rate": 0.1, 
    "cosine_scheduler": True,
    "scheduler_final_lr": 1e-5,
    "n_latent": 32, 
    "n_latent_attribute_ordered": 512,
    "reconstruction_penalty": 1000.0,
    "attribute_nn_width": 64,
    "attribute_nn_depth":6, 
    "attribute_nn_lr": 0.001, 
    "attribute_nn_wd": 4e-8,
    "latent_lr": 0.0001,
    "latent_wd": 0.001,
    "unknown_attribute_penalty": 10000.0,
    "decoder_width": 64,
    "decoder_depth": 1,  
    "decoder_activation": False,
    "attribute_nn_activation": False,
    "unknown_attributes": False,
    "decoder_lr": 0.001,
    "decoder_wd": 0.01,
    "max_epochs": 1000,
    "early_stopping_patience": 10,
    "ordered_attributes_key": "perturbation_neighbors",
    "n_latent_attribute_categorical": 16,
}

